volumes:
  grafana:
  data:
services:
  grafana:
    image: registry.hub.docker.com/grafana/grafana-oss:latest
    container_name: grafana
    env_file: "grafana.env"
    restart: unless-stopped
    volumes:
      - grafana:/var/lib/grafana
    networks:
      - grafanaV6
    ports:
     - '4000:3000'
  db:
    image: docker.io/mariadb
    env_file: "db.env"
    restart: unless-stopped
    volumes:
      - data:/var/lib/mysql
    networks:
      - grafanaV6
    ports:
      - "3306:3306"
networks:
  grafanaV6:
    driver: bridge
